name: "Build & Push (to Cachix)"


on:
    push:
    schedule:
        - cron: '0 1 * * *'


#
# The "Build" step is the key
# difference between these two types
# of builds.
#
# Sadly YAML anchors seems not work
# in GitHub Actions.
#

jobs:

    builds-parallel:
        runs-on: ubuntu-latest
        steps:
            - uses: cachix/install-nix-action@v17
              with:
                  nix_path: "nixpkgs=channel:nixpkgs-unstable"
            - name: "Install tools"
              run: |
                nix-env -f '<nixpkgs>' -iA nix-build-uncached
            - uses: cachix/cachix-action@v10
              with:
                  name: "nuirrce"
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
                  cachixArgs: "-j8 -c5"
            - uses: actions/checkout@v3
              with:
                  ref: "master"
            - name: "Build"
              run: |
                  nix flake update
                  nix-build-uncached workflow-builds.nix \
                    -A parallel \
                    -build-flags '--print-build-logs'
            - name: "Cleanup"
              run: |
                  nix-collect-garbage -d


    builds-sequential:
        runs-on: ubuntu-latest
        steps:
            - uses: cachix/install-nix-action@v17
              with:
                  nix_path: "nixpkgs=channel:nixpkgs-unstable"
            - name: "Install tools"
              run: |
                nix-env -f '<nixpkgs>' -iA nix-build-uncached fish
            - uses: cachix/cachix-action@v10
              with:
                  name: "nuirrce"
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
                  cachixArgs: "-j8 -c5"
            - uses: actions/checkout@v3
              with:
                  ref: "master"
            - name: "Build"
              run: |
                  nix flake update
                  fish _scripts/seq-build.fish workflow-builds.nix sequential
            - name: "Cleanup"
              run: |
                  nix-collect-garbage -d

